
import static java.lang.Math.random;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brian
 */
public class order extends javax.swing.JFrame {
    private static Login frame = new Login();
    private static CheckOrder checkPage = new CheckOrder();
    private static MyDBConnection mdbc;
    private static java.sql.Statement stmt;
    private static String cust_id = "";
    private static String cust_name = "";
    private static String shop_name = "";
    private static DateFormat dateFormat2 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    
    /**
     * Creates new form order
     */
    public order(Login fr) {
        initComponents();
        try{
            mdbc = new MyDBConnection();
            mdbc.init();
            Connection conn=mdbc.getMyConnection();
            stmt= conn.createStatement();
        }catch(SQLException e){}

        setTitle("HiTEA");
        frame = fr;  
        getCustomerName();
        getCustomerID();
        getShopNameForDelivery();
        NameShown.setText("Hi, " + cust_name + ". Your ID: " + cust_id + " Delivery Shop: " + shop_name);
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        NameShown = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        DrinkTtile = new javax.swing.JLabel();
        FoodTitle = new javax.swing.JLabel();
        DrinkLabel1 = new javax.swing.JCheckBox();
        DrinkLabel2 = new javax.swing.JCheckBox();
        DrinkLabel3 = new javax.swing.JCheckBox();
        DrinkLabel4 = new javax.swing.JCheckBox();
        FoodLabel5 = new javax.swing.JCheckBox();
        FoodLabel6 = new javax.swing.JCheckBox();
        FoodLabel7 = new javax.swing.JCheckBox();
        FoodLabel8 = new javax.swing.JCheckBox();
        L1 = new javax.swing.JLabel();
        L1BTN1 = new javax.swing.JButton();
        L1BTN11 = new javax.swing.JButton();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L2BTN2 = new javax.swing.JButton();
        L2BTN22 = new javax.swing.JButton();
        L3BTN3 = new javax.swing.JButton();
        L3BTN33 = new javax.swing.JButton();
        L4BTN4 = new javax.swing.JButton();
        L4BTN44 = new javax.swing.JButton();
        L5 = new javax.swing.JLabel();
        L5BTN5 = new javax.swing.JButton();
        L5BTN55 = new javax.swing.JButton();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L6BTN6 = new javax.swing.JButton();
        L8BTN88 = new javax.swing.JButton();
        L7BTN7 = new javax.swing.JButton();
        L7BTN77 = new javax.swing.JButton();
        L8BTN8 = new javax.swing.JButton();
        L6BTN66 = new javax.swing.JButton();
        CountLabel = new javax.swing.JLabel();
        CountLabel2 = new javax.swing.JLabel();
        OrderBtn = new javax.swing.JButton();
        DrinkLabel11 = new javax.swing.JLabel();
        DrinkLabel22 = new javax.swing.JLabel();
        DrinkLabel33 = new javax.swing.JLabel();
        DrinkLabel44 = new javax.swing.JLabel();
        FoodLabel55 = new javax.swing.JLabel();
        FoodLabel66 = new javax.swing.JLabel();
        FoodLabel77 = new javax.swing.JLabel();
        FoodLabel88 = new javax.swing.JLabel();
        CheckBill = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(102, 0, 255));
        Title.setText("Welcome to HiTEA");

        NameShown.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NameShown.setText("Hi, (Name) Your ID: (Customer_id) Delivery Shop: (01)");

        DrinkTtile.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        DrinkTtile.setText("Drinking");

        FoodTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        FoodTitle.setText("Food");

        DrinkLabel1.setText("000001 Mango Juice");
        DrinkLabel1.setToolTipText("");
        DrinkLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkLabel1ActionPerformed(evt);
            }
        });

        DrinkLabel2.setText("000002 Apple Juice");
        DrinkLabel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkLabel2ActionPerformed(evt);
            }
        });

        DrinkLabel3.setText("000003 Orange Juice");

        DrinkLabel4.setText("000004 Matcha Latte");

        FoodLabel5.setText("000005French Fries ");
        FoodLabel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodLabel5ActionPerformed(evt);
            }
        });

        FoodLabel6.setText("000006Fish & Chips");

        FoodLabel7.setText("000007Beef Noodles");

        FoodLabel8.setText("000008Curry Beef Rice ");

        L1.setText("0");

        L1BTN1.setText("+");
        L1BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1BTN1ActionPerformed(evt);
            }
        });

        L1BTN11.setText("-");
        L1BTN11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1BTN11ActionPerformed(evt);
            }
        });

        L2.setText("0");

        L3.setText("0");

        L4.setText("0");

        L2BTN2.setText("+");
        L2BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2BTN2ActionPerformed(evt);
            }
        });

        L2BTN22.setText("-");
        L2BTN22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L2BTN22ActionPerformed(evt);
            }
        });

        L3BTN3.setText("+");
        L3BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3BTN3ActionPerformed(evt);
            }
        });

        L3BTN33.setText("-");
        L3BTN33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L3BTN33ActionPerformed(evt);
            }
        });

        L4BTN4.setText("+");
        L4BTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L4BTN4ActionPerformed(evt);
            }
        });

        L4BTN44.setText("-");
        L4BTN44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L4BTN44ActionPerformed(evt);
            }
        });

        L5.setText("0");

        L5BTN5.setText("+");
        L5BTN5.setToolTipText("");
        L5BTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L5BTN5ActionPerformed(evt);
            }
        });

        L5BTN55.setText("-");
        L5BTN55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L5BTN55ActionPerformed(evt);
            }
        });

        L6.setText("0");

        L7.setText("0");

        L8.setText("0");

        L6BTN6.setText("+");
        L6BTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L6BTN6ActionPerformed(evt);
            }
        });

        L8BTN88.setText("-");
        L8BTN88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L8BTN88ActionPerformed(evt);
            }
        });

        L7BTN7.setText("+");
        L7BTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L7BTN7ActionPerformed(evt);
            }
        });

        L7BTN77.setText("-");
        L7BTN77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L7BTN77ActionPerformed(evt);
            }
        });

        L8BTN8.setText("+");
        L8BTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L8BTN8ActionPerformed(evt);
            }
        });

        L6BTN66.setText("-");
        L6BTN66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L6BTN66ActionPerformed(evt);
            }
        });

        CountLabel.setText("Total Count:");

        CountLabel2.setText("0");

        OrderBtn.setText("Order");
        OrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBtnActionPerformed(evt);
            }
        });

        DrinkLabel11.setText("16");
        DrinkLabel11.setToolTipText("");

        DrinkLabel22.setText("14");

        DrinkLabel33.setText("14");

        DrinkLabel44.setText("21");

        FoodLabel55.setText("10");

        FoodLabel66.setText("18");

        FoodLabel77.setText("24");

        FoodLabel88.setText("26");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DrinkTtile)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(DrinkLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DrinkLabel11))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(DrinkLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DrinkLabel33))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(DrinkLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DrinkLabel44))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(DrinkLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DrinkLabel22)))
                                .addGap(67, 67, 67)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(L4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L4BTN4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L4BTN44))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(L2)
                                            .addComponent(L3))
                                        .addGap(6, 6, 6)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                .addComponent(L3BTN3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(L3BTN33))
                                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                .addComponent(L2BTN2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(L2BTN22))))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(L1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L1BTN1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L1BTN11)))
                                .addGap(22, 22, 22)))
                        .addGap(27, 27, 27)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FoodLabel8)
                            .addComponent(FoodLabel7)
                            .addComponent(FoodLabel6)
                            .addComponent(FoodLabel5)
                            .addComponent(FoodTitle)))
                    .addComponent(CountLabel))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FoodLabel88)
                            .addComponent(FoodLabel77)
                            .addComponent(FoodLabel66)
                            .addComponent(FoodLabel55))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(L8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L7BTN7)
                                    .addComponent(L8BTN8)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(L5)
                                        .addGap(18, 18, 18)
                                        .addComponent(L5BTN5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(L6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(L6BTN6)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L7BTN77)
                            .addComponent(L5BTN55)
                            .addComponent(L6BTN66)
                            .addComponent(L8BTN88)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CountLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(OrderBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DrinkTtile)
                            .addComponent(FoodTitle))
                        .addGap(30, 30, 30)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DrinkLabel1)
                                    .addComponent(FoodLabel5)
                                    .addComponent(L1)
                                    .addComponent(L1BTN1)
                                    .addComponent(L1BTN11)
                                    .addComponent(DrinkLabel11)
                                    .addComponent(FoodLabel55))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DrinkLabel2)
                                    .addComponent(L2)
                                    .addComponent(L2BTN2)
                                    .addComponent(DrinkLabel22)
                                    .addComponent(L2BTN22)
                                    .addComponent(FoodLabel66)
                                    .addComponent(FoodLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DrinkLabel3)
                                        .addComponent(L3)
                                        .addComponent(L3BTN3)
                                        .addComponent(L3BTN33)
                                        .addComponent(DrinkLabel33)
                                        .addComponent(FoodLabel77))
                                    .addComponent(FoodLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DrinkLabel4)
                                    .addComponent(L4)
                                    .addComponent(L4BTN4)
                                    .addComponent(L4BTN44)
                                    .addComponent(FoodLabel8)
                                    .addComponent(DrinkLabel44)
                                    .addComponent(FoodLabel88)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(L5)
                                    .addComponent(L5BTN5))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(L6)
                                    .addComponent(L6BTN6))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(L7)
                                    .addComponent(L7BTN7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(L8)
                                    .addComponent(L8BTN8)))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(L5BTN55)
                        .addGap(18, 18, 18)
                        .addComponent(L6BTN66)
                        .addGap(18, 18, 18)
                        .addComponent(L7BTN77)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L8BTN88)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountLabel)
                    .addComponent(CountLabel2)
                    .addComponent(OrderBtn))
                .addGap(52, 52, 52))
        );
        jLayeredPane1.setLayer(DrinkTtile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DrinkLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DrinkLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DrinkLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DrinkLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L1BTN1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L1BTN11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L2BTN2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L2BTN22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L3BTN3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L3BTN33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L4BTN4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L4BTN44, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L5BTN5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L5BTN55, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L6BTN6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L8BTN88, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L7BTN7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L7BTN77, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L8BTN8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(L6BTN66, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CountLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CountLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(OrderBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DrinkLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DrinkLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DrinkLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DrinkLabel44, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodLabel55, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodLabel66, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodLabel77, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(FoodLabel88, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CheckBill.setText("Check");
        CheckBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBillActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameShown)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBill)))
                        .addGap(157, 565, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameShown)
                    .addComponent(CheckBill))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void CheckBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBillActionPerformed
        // TODO add your handling code here:
        checkPage = new CheckOrder();
        checkPage.setVisible(true);
        JTable table = checkPage.getTable();
        boolean valid = true;
        ResultSet rs = null;
        try{
            rs = CheckOrderDBByCustomerId();
            if(rs.next()){
                valid = true;
            }else{
                valid = false;
            }
            if(valid){
                table.setModel(DbUtils.resultSetToTableModel(CheckOrderDBByCustomerId()));
            }else{
                JOptionPane.showMessageDialog(
                null,
                "You don't have any food ordering in HiTEA",
                "No Record!!",
                JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(SQLException e){}
 
    }//GEN-LAST:event_CheckBillActionPerformed

    private void OrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBtnActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(CountLabel2.getText()) <= 0){
            JOptionPane.showMessageDialog(
                null,
                "You didn't order anything. Please order food, now. ",
                "Order Failed!!",
                JOptionPane.INFORMATION_MESSAGE);
        }else{
            ArrayList<String> food_list = new ArrayList<String>();
            ArrayList<Double> total_price = new ArrayList<Double>();
            String food = "";
            //String orderId = "";
            Random random = new Random();
            Date newdate = new Date();

            if(Integer.parseInt(L1.getText()) > 0){
                food = food.concat(DrinkLabel1.getText() + " "+ L1.getText() + " " +Double.toString(Double.parseDouble(L1.getText())*Double.parseDouble(DrinkLabel11.getText()))+ "\n");
                food_list.add(DrinkLabel1.getText());
                total_price.add(Double.parseDouble(L1.getText())*Double.parseDouble(DrinkLabel11.getText()));
            }
            if(Integer.parseInt(L2.getText()) > 0){
                food = food.concat(DrinkLabel2.getText() + " "+ L2.getText() + " " + Double.toString(Double.parseDouble(L2.getText())*Double.parseDouble(DrinkLabel22.getText()))+ "\n");
                food_list.add(DrinkLabel2.getText());
                total_price.add(Double.parseDouble(L2.getText())*Double.parseDouble(DrinkLabel22.getText()));
            }
            if(Integer.parseInt(L3.getText()) > 0){
                food = food.concat(DrinkLabel3.getText() + " "+ L3.getText() + " " + Double.toString(Double.parseDouble(L3.getText())*Double.parseDouble(DrinkLabel33.getText()))+"\n");
                food_list.add(DrinkLabel3.getText());
                total_price.add(Double.parseDouble(L3.getText())*Double.parseDouble(DrinkLabel33.getText()));
            }
            if(Integer.parseInt(L4.getText()) > 0){
                food = food.concat(DrinkLabel4.getText() + " "+ L4.getText() + " " + Double.toString(Double.parseDouble(L4.getText())*Double.parseDouble(DrinkLabel44.getText())) +"\n");
                food_list.add(DrinkLabel4.getText());
                total_price.add(Double.parseDouble(L4.getText())*Double.parseDouble(DrinkLabel44.getText()));
            }
            if(Integer.parseInt(L5.getText()) > 0){
                food = food.concat(FoodLabel5.getText() + " "+ L5.getText() + " " + Double.toString(Double.parseDouble(L5.getText())*Double.parseDouble(FoodLabel55.getText())) + "\n");
                food_list.add(FoodLabel5.getText());
                total_price.add(Double.parseDouble(L5.getText())*Double.parseDouble(FoodLabel55.getText()));
            }
            if(Integer.parseInt(L6.getText()) > 0){
                food = food.concat(FoodLabel6.getText() + " "+ L6.getText() + " " + Double.toString(Double.parseDouble(L6.getText())*Double.parseDouble(FoodLabel66.getText())) +"\n");
                food_list.add(FoodLabel6.getText());
                total_price.add(Double.parseDouble(L6.getText())*Double.parseDouble(FoodLabel66.getText()));
            }
            if(Integer.parseInt(L7.getText()) > 0){
                food = food.concat(FoodLabel7.getText() + " "+ L7.getText() + " " + Double.toString(Double.parseDouble(L7.getText())*Double.parseDouble(FoodLabel77.getText())) +"\n");
                food_list.add(FoodLabel7.getText());
                total_price.add(Double.parseDouble(L7.getText())*Double.parseDouble(FoodLabel77.getText()));
            }
            if(Integer.parseInt(L8.getText()) > 0){
                food = food.concat(FoodLabel8.getText() + " "+ L8.getText() + " " + Double.toString(Double.parseDouble(L8.getText())*Double.parseDouble(FoodLabel88.getText())) +"\n");
                food_list.add(FoodLabel8.getText());
                total_price.add(Double.parseDouble(L8.getText())*Double.parseDouble(FoodLabel88.getText()));
            }

            int result = JOptionPane.showConfirmDialog(
                null,
                "-----HiTEA Order Confirm------\n"+ dateFormat2.format(newdate) +
                "\nHi, " + cust_name + "  ID: " + cust_id +
                "\n----Order List-----\n" + food +
                "----------------------\n"+
                "Total Price: " + CountLabel2.getText() +
                "\nPayment Method: Pay on delivery\nThank you for your support!",
                "Order Confirm!!",
                JOptionPane.YES_NO_OPTION);
            if (result == 0){
                boolean valid = true;
                int num = 000001;
                while(valid){
                    num = random.nextInt(999999) % (999999 - 000001 + 1);
                    if(VerifyOrderID(Integer.toString(num))){
                        valid = true;
                    }else{
                        valid = false;
                    }
                }

                //insert order_id,customer_id,date,Food_list,price
                InsertOrderRecord(Integer.toString(num),dateFormat2.format(newdate),
                    food_list.toString(), Double.parseDouble(CountLabel2.getText()));

                System.out.println("yes");
            }else{
                System.out.println("no");
            }
        }

    }//GEN-LAST:event_OrderBtnActionPerformed

    private void L6BTN66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L6BTN66ActionPerformed
        // TODO add your handling code here:
        L6.setText(Integer.toString(Integer.parseInt(L6.getText()) - 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L6BTN66ActionPerformed

    private void L8BTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L8BTN8ActionPerformed
        // TODO add your handling code here:
        L8.setText(Integer.toString(Integer.parseInt(L8.getText()) + 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L8BTN8ActionPerformed

    private void L7BTN77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L7BTN77ActionPerformed
        // TODO add your handling code here:
        L7.setText(Integer.toString(Integer.parseInt(L7.getText()) - 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L7BTN77ActionPerformed

    private void L7BTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L7BTN7ActionPerformed
        // TODO add your handling code here:
        L7.setText(Integer.toString(Integer.parseInt(L7.getText()) + 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L7BTN7ActionPerformed

    private void L8BTN88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L8BTN88ActionPerformed
        // TODO add your handling code here:
        L8.setText(Integer.toString(Integer.parseInt(L8.getText()) - 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L8BTN88ActionPerformed

    private void L6BTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L6BTN6ActionPerformed
        // TODO add your handling code here:
        L6.setText(Integer.toString(Integer.parseInt(L6.getText()) + 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L6BTN6ActionPerformed

    private void L5BTN55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L5BTN55ActionPerformed
        // TODO add your handling code here:
        L5.setText(Integer.toString(Integer.parseInt(L5.getText()) - 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L5BTN55ActionPerformed

    private void L5BTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L5BTN5ActionPerformed
        // TODO add your handling code here:
        L5.setText(Integer.toString(Integer.parseInt(L5.getText()) + 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L5BTN5ActionPerformed

    private void L4BTN44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L4BTN44ActionPerformed
        // TODO add your handling code here:
        L4.setText(Integer.toString(Integer.parseInt(L4.getText()) - 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L4BTN44ActionPerformed

    private void L4BTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L4BTN4ActionPerformed
        // TODO add your handling code here:
        L4.setText(Integer.toString(Integer.parseInt(L4.getText()) + 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L4BTN4ActionPerformed

    private void L3BTN33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3BTN33ActionPerformed
        // TODO add your handling code here:
        L3.setText(Integer.toString(Integer.parseInt(L3.getText()) - 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L3BTN33ActionPerformed

    private void L3BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L3BTN3ActionPerformed
        // TODO add your handling code here:
        L3.setText(Integer.toString(Integer.parseInt(L3.getText()) + 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L3BTN3ActionPerformed

    private void L2BTN22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2BTN22ActionPerformed
        // TODO add your handling code here:
        L2.setText(Integer.toString(Integer.parseInt(L2.getText()) - 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L2BTN22ActionPerformed

    private void L2BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L2BTN2ActionPerformed
        // TODO add your handling code here:
        L2.setText(Integer.toString(Integer.parseInt(L2.getText()) + 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L2BTN2ActionPerformed

    private void L1BTN11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1BTN11ActionPerformed
        // TODO add your handling code here:
        L1.setText(Integer.toString(Integer.parseInt(L1.getText()) - 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L1BTN11ActionPerformed

    private void L1BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1BTN1ActionPerformed
        // TODO add your handling code here:
        L1.setText(Integer.toString(Integer.parseInt(L1.getText()) + 1));
        CountLabel2.setText(Integer.toString(Integer.parseInt(L1.getText()) * Integer.parseInt(DrinkLabel11.getText()) +
            Integer.parseInt(L2.getText()) * Integer.parseInt(DrinkLabel22.getText()) +
            Integer.parseInt(L3.getText()) * Integer.parseInt(DrinkLabel33.getText()) +
            Integer.parseInt(L4.getText()) * Integer.parseInt(DrinkLabel44.getText()) +
            Integer.parseInt(L5.getText()) * Integer.parseInt(FoodLabel55.getText()) +
            Integer.parseInt(L6.getText()) * Integer.parseInt(FoodLabel66.getText()) +
            Integer.parseInt(L7.getText()) * Integer.parseInt(FoodLabel77.getText()) +
            Integer.parseInt(L8.getText()) * Integer.parseInt(FoodLabel88.getText())));
    }//GEN-LAST:event_L1BTN1ActionPerformed

    private void FoodLabel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodLabel5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodLabel5ActionPerformed

    private void DrinkLabel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkLabel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrinkLabel2ActionPerformed

    private void DrinkLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkLabel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrinkLabel1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mdbc.close(stmt);
        mdbc.destroy();
        frame.setVisible(true);
        frame.clear();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void getCustomerName(){
        ResultSet rs2 = getResultFromCustomer(frame.getUsername());
        try{
            if (rs2.next()){
                cust_name = rs2.getString("name");
            }
        }catch(SQLException e){}
    }
    
    public void getCustomerID(){
        //String cust_id = "";
        ResultSet rs2 = getResultFromCustomer(frame.getUsername());
        try{
            if (rs2.next()){
                cust_id = rs2.getString("customerID");
            }
        }catch(SQLException e){}
        //return cust_id;
    }
    
    public void getShopNameForDelivery(){
        String shop_id = "";
        ResultSet rs2 = getResultFromCustomer(frame.getUsername());
        String SQLStatement = "Select Shop_ID, Shop_Name from shop where Shop_ID = ";
        try{
            if (rs2.next()){
                shop_id = rs2.getString("Shop_ID");
            }
            SQLStatement += quotate(shop_id) + ";";
            ResultSet rs3 = stmt.executeQuery(SQLStatement);
            if (rs3.next()){
                shop_name = rs3.getString("Shop_Name");
            }
        }catch(SQLException e){}
    }
    
    public ResultSet getResultFromCustomer(String username) {
        
        ResultSet rs=null;
        try{
            String SQLStatement = "Select * from customer where customerID" + " = " + quotate(username) + ";";
            rs = stmt.executeQuery(SQLStatement);
        }catch(SQLException e){}
        
        return rs;
        
    }
    
    public String quotate(String content){
    
        return "'"+content+"'";
    }
    
    public String quotate1(String content){
    
        return "\""+content+"\"";
    }
    public boolean VerifyOrderID(String num){
            ResultSet rs = CheckOrderDB(num);
            boolean valid = true;
                        try{
                            if(rs.next()){
                                valid = true;
                            }else{
                                valid = false;
                            }
                        }catch(SQLException e){}
            return valid;
    }
    
    public ResultSet CheckOrderDB(String orderid){
        
        ResultSet rs=null;
        try{
            String SQLStatement = "Select * from `order` where Order_id" + " = " + quotate(orderid) + ";";
            rs = stmt.executeQuery(SQLStatement);
        }catch(SQLException e){}
        
        return rs;
    }
    
    public ResultSet CheckOrderDBByCustomerId(){
        ResultSet rs=null;
        try{
            String SQLStatement = "Select `order`.Order_id, `order`.`date`,  `order`.`Food_List`, `order`.`Total_Price`, `employee`.`name` " +
                                   "from `order` left join (`customer` left join `employee` on `customer`.`Shop_ID` = `employee`.`Shop_ID`) " + 
                                   "on (`order`.`customerID`=`customer`.`customerID`) "  + "Where `order`.`customerID` =  " + quotate1(cust_id) + ";";

            rs = stmt.executeQuery(SQLStatement);
        }catch(SQLException e){}
        
        return rs;
    }
    
    public void InsertOrderRecord(String orderid, String newdate, String foodlist, Double price){
        String insertStr = "";
        try{
            //insert order_id,customer_id,date,Food_list,price
            insertStr = "Insert into `order` VALUES (" + quotate(orderid) + ", " + quotate(cust_id) + ", " + quotate(newdate) +  ", " + quotate(foodlist) + ", " +  price + ")";
            int done = stmt.executeUpdate(insertStr);
            JOptionPane.showMessageDialog(
                            null,
                            "Successfully order ",
                            "Success!!",
                            JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                        e.printStackTrace();
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckBill;
    private javax.swing.JLabel CountLabel;
    private javax.swing.JLabel CountLabel2;
    private javax.swing.JCheckBox DrinkLabel1;
    private javax.swing.JLabel DrinkLabel11;
    private javax.swing.JCheckBox DrinkLabel2;
    private javax.swing.JLabel DrinkLabel22;
    private javax.swing.JCheckBox DrinkLabel3;
    private javax.swing.JLabel DrinkLabel33;
    private javax.swing.JCheckBox DrinkLabel4;
    private javax.swing.JLabel DrinkLabel44;
    private javax.swing.JLabel DrinkTtile;
    private javax.swing.JCheckBox FoodLabel5;
    private javax.swing.JLabel FoodLabel55;
    private javax.swing.JCheckBox FoodLabel6;
    private javax.swing.JLabel FoodLabel66;
    private javax.swing.JCheckBox FoodLabel7;
    private javax.swing.JLabel FoodLabel77;
    private javax.swing.JCheckBox FoodLabel8;
    private javax.swing.JLabel FoodLabel88;
    private javax.swing.JLabel FoodTitle;
    private javax.swing.JLabel L1;
    private javax.swing.JButton L1BTN1;
    private javax.swing.JButton L1BTN11;
    private javax.swing.JLabel L2;
    private javax.swing.JButton L2BTN2;
    private javax.swing.JButton L2BTN22;
    private javax.swing.JLabel L3;
    private javax.swing.JButton L3BTN3;
    private javax.swing.JButton L3BTN33;
    private javax.swing.JLabel L4;
    private javax.swing.JButton L4BTN4;
    private javax.swing.JButton L4BTN44;
    private javax.swing.JLabel L5;
    private javax.swing.JButton L5BTN5;
    private javax.swing.JButton L5BTN55;
    private javax.swing.JLabel L6;
    private javax.swing.JButton L6BTN6;
    private javax.swing.JButton L6BTN66;
    private javax.swing.JLabel L7;
    private javax.swing.JButton L7BTN7;
    private javax.swing.JButton L7BTN77;
    private javax.swing.JLabel L8;
    private javax.swing.JButton L8BTN8;
    private javax.swing.JButton L8BTN88;
    private javax.swing.JLabel NameShown;
    private javax.swing.JButton OrderBtn;
    private javax.swing.JLabel Title;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
